server:
  port: ${SERVER_PORT:9600}
spring:
  lifecycle:
    # 部署时k8s关闭钩子切记需要配置
    timeout-per-shutdown-phase: 3m
  # 线程池配置
  task:
    execution:
      pool:
        core-size: 24
        max-size: 100
  servlet:
    multipart:
      max-file-size: 4MB